#!/usr/bin/env bash
####################################################################
# Process the template into its bash script
#
# - Idempotent
####################################################################
set -euo pipefail

src=per-user
dst=/usr/local/bin
tmp=tmp

cat $src/${APP_PROVISION_USER}.tpl \
    |sed "s,APP_GROUP_ADMINS,${APP_GROUP_ADMINS},g" \
    |sed "s,APP_NAME,${APP_NAME},g" \
    |sed "s,APP_GROUP_USERS,${APP_GROUP_USERS},g" \
    |sed "s,APP_OCI_TEST_IMAGE,${APP_OCI_TEST_IMAGE},g" \
    |tee $src/${APP_PROVISION_USER}

exit $?
#######

cat $src/${APP_PROVISION_USER}.tpl \
    |sed "s,APP_GROUP_ADMINS,${APP_GROUP_ADMINS},g" \
    |sed "s,APP_NAME,${APP_NAME},g" \
    |sed "s,APP_GROUP_USERS,${APP_GROUP_USERS},g" \
    |sed "s,APP_OCI_TEST_IMAGE,${APP_OCI_TEST_IMAGE},g" \
    |sed '/^#/d' >$tmp

cat <<EOH |cat - $tmp |tee $src/${APP_PROVISION_USER}
#!/usr/bin/env bash
###############################
# AUTOGENERATED : DO NOT EDIT
###############################
EOH

rm $tmp
