#!/bin/bash
################################################################
# Brute-force method of provisioning unique subids for a user.
# This is not necessary if user is local and has login shell.
# Podman provisions subids automatically for local users upon 
# creation if user has a login shell.
#
# Script is a mod of that generated by Deepseek on 2025-05-dd
################################################################
[[ $(whoami) == 'root' ]] || {
    echo Must RUN AS root 
    exit 11
}
set -e

USERNAME="${1:-podmaners}"  # Change this to your service account
BASE_UID=100000             # Start of subUID range (default for Podman)
RANGE_SIZE=65536            # 65k IDs (Podman default)

# Check if user exists
if ! id "$USERNAME" &>/dev/null; then
    echo "Error: User '$USERNAME' does not exist!"
    exit 1
fi

# Function to find next available range
find_next_range() {
    local file=$1
    local last_end=$BASE_UID

    # Extract and sort existing ranges
    while IFS=: read -r _ start count; do
        end=$((start + count))
        if [[ $end -gt $last_end ]]; then
            last_end=$end
        fi
    done < <(grep -v "^$USERNAME:" "$file" 2>/dev/null | sort -t: -k2 -n)

    echo "$last_end"
}

# Assign subUIDs
assign_subids() {
    local file=$1
    local type=$2
    local next_start=$(find_next_range "$file")

    # Check if user already has a range
    if grep -q "^$USERNAME:" "$file"; then
        echo "✅ $USERNAME already has $type ranges in $file"
        return
    fi

    # Add new entry
    echo "$USERNAME:$next_start:$RANGE_SIZE" | sudo tee -a "$file" >/dev/null
    echo "➕ Added $type range $next_start-$((next_start + RANGE_SIZE - 1)) to $file"
}

# Main
assign_subids "/etc/subuid" "subUID"
assign_subids "/etc/subgid" "subGID"

# Enable lingering (for systemd)
sudo loginctl enable-linger "$USERNAME"

# Verify
echo -e "\n🔍 Current ranges for $USERNAME:"
grep "^$USERNAME:" /etc/subuid /etc/subgid || {
    echo "❌ Failed to assign ranges!"
    exit 1
}

# Optional: Migrate Podman storage
sudo -u "$USERNAME" podman system migrate 2>/dev/null && \
    echo "🔄 Podman storage migrated" || \
    echo "⚠️ Podman migration skipped (not configured yet)"