---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-fileserver
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:alpine
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: static-content
          mountPath: /usr/share/nginx/html
      resources: {}
    - name: health-endpoint
      image: docker.io/python:3-alpine
      command: ["python3", "-u", "-c"]
      args:
        - |
          import http.server, socketserver, json, time, socket
          class Handler(http.server.BaseHTTPRequestHandler):
              def do_GET(self):
                  if self.path != '/health':
                      self.send_error(404)
                      return
                  response = {
                      'client_ip': self.client_address[0],
                      'request_path': self.path,
                      'hostname': socket.gethostname(),
                      'timestamp': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
                      'server_ip': socket.gethostbyname(socket.gethostname())
                  }
                  self.send_response(200)
                  self.send_header("Content-Type", "application/json")
                  self.end_headers()
                  self.wfile.write(json.dumps(response).encode())
          with socketserver.TCPServer(("", 8080), Handler) as httpd:
              httpd.serve_forever()
      ports:
        - containerPort: 8080
          hostPort: 8081
      resources: {}
  volumes:
    - name: static-content
      hostPath:
        path: /srv/nginx-fileserver
        type: Directory

